# Generated by Django 3.1.1 on 2021-09-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Location'},
        ),
        migrations.AlterModelOptions(
            name='propertytype',
            options={'verbose_name_plural': 'My Property Type'},
        ),
        migrations.AddField(
            model_name='property',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2021-08-09'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
